### ISSUE TITLE
Question Julien 20/05/2022

### ISSUE THREAD

**Issue by ClemLcs** [Bde-Saintonge/Site#60]
Poser la question à Julien sur si on delete un user à la fin de l'année

**Comment by ClemLcs** [comment]
Faire un script Powershell pour edit les groupes AD dans la BDD

**Comment by jul-fls** [comment]
> Faire un script Powershell pour edit les groupes AD dans la BDD

pas tout compris là

**Comment by ClemLcs** [comment]
> On en parle Lundi

**Comment by jul-fls** [comment]
> > On en parle Lundi

ok
